# Generated by Django 6.0.6 on 2026-07-01 03:53

import apps.fuentes.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0007_limpiar_metadatos_documentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, validators=[apps.fuentes.validators.validar_codigo_fuente])),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('url_base', models.URLField(validators=[apps.fuentes.validators.validar_url_fuente])),
                ('url_consulta_principal', models.URLField(blank=True, default='', validators=[apps.fuentes.validators.validar_url_fuente])),
                ('tipo_fuente', models.CharField(choices=[('PORTAL_WEB', 'Portal web'), ('API', 'API'), ('RSS', 'RSS'), ('REPOSITORIO', 'Repositorio documental')], default='PORTAL_WEB', max_length=20)),
                ('motor_consulta', models.CharField(choices=[('HTTPX', 'HTTPX / HTML estático'), ('PLAYWRIGHT', 'Playwright / JavaScript')], default='HTTPX', max_length=20)),
                ('requiere_javascript', models.BooleanField(default=False)),
                ('requiere_autenticacion', models.BooleanField(default=False)),
                ('frecuencia_consulta', models.CharField(choices=[('MANUAL', 'Manual'), ('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal')], default='MANUAL', max_length=20)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('ultimo_estado_prueba', models.CharField(choices=[('NO_PROBADO', 'No probado'), ('DISPONIBLE', 'Disponible'), ('ERROR', 'Error')], default='NO_PROBADO', max_length=20)),
                ('ultima_prueba_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_codigo_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ultimo_mensaje_prueba', models.TextField(blank=True, default='')),
                ('ultimo_error_prueba', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entidad_emisora_predeterminada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuentes_predeterminadas', to='catalogos.entidademisora')),
                ('materia_predeterminada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuentes_predeterminadas', to='catalogos.materia')),
            ],
            options={
                'verbose_name': 'fuente web',
                'verbose_name_plural': 'fuentes web',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='FuenteSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, validators=[apps.fuentes.validators.validar_codigo_fuente])),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('url_listado', models.URLField(validators=[apps.fuentes.validators.validar_url_fuente])),
                ('url_busqueda', models.URLField(blank=True, default='', validators=[apps.fuentes.validators.validar_url_fuente])),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materia_predeterminada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secciones_fuente_predeterminadas', to='catalogos.materia')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='fuentes.fuenteweb')),
            ],
            options={
                'verbose_name': 'sección de fuente',
                'verbose_name_plural': 'secciones de fuentes',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='EjecucionFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ejecucion', models.CharField(choices=[('PRUEBA_CONEXION', 'Prueba de conexión'), ('EJECUCION_MANUAL', 'Ejecución manual'), ('EJECUCION_PROGRAMADA', 'Ejecución programada')], default='PRUEBA_CONEXION', max_length=30)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('EXITOSA', 'Exitosa'), ('PARCIAL', 'Parcial'), ('ERROR', 'Error')], default='EN_PROCESO', max_length=20)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('codigo_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('documentos_encontrados', models.PositiveIntegerField(default=0)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('detalle_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones_fuentes_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones', to='fuentes.fuenteseccion')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='fuentes.fuenteweb')),
            ],
            options={
                'verbose_name': 'ejecución de fuente',
                'verbose_name_plural': 'ejecuciones de fuentes',
                'ordering': ('-inicio', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='fuenteseccion',
            constraint=models.UniqueConstraint(fields=('fuente', 'codigo'), name='unique_codigo_por_fuente'),
        ),
    ]
