# Generated by Django 6.0.6 on 2026-07-02 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuentes', '0001_initial'),
        ('normativa', '0007_alter_documento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionfuente',
            name='documentos_descargados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejecucionfuente',
            name='documentos_duplicados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejecucionfuente',
            name='documentos_omitidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejecucionfuente',
            name='duracion_ms',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejecucionfuente',
            name='paginas_revisadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejecucionfuente',
            name='tarea_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ejecucionfuente',
            name='total_errores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HallazgoFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('DESCUBIERTO', 'Descubierto'), ('DESCARGADO', 'Descargado'), ('DUPLICADO', 'Duplicado'), ('OMITIDO', 'Omitido'), ('ERROR', 'Error')], db_index=True, default='DESCUBIERTO', max_length=20)),
                ('url', models.URLField(max_length=2000)),
                ('titulo_encontrado', models.CharField(blank=True, default='', max_length=500)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=255)),
                ('codigo_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=150)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('hash_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('detalle_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos_fuente', to='normativa.documento')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='fuentes.ejecucionfuente')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos', to='fuentes.fuenteweb')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos', to='fuentes.fuenteseccion')),
            ],
            options={
                'verbose_name': 'hallazgo de fuente',
                'verbose_name_plural': 'hallazgos de fuentes',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['fuente', 'estado', '-created_at'], name='fuente_hallazgo_estado_idx')],
                'constraints': [models.UniqueConstraint(fields=('ejecucion', 'url'), name='fuentes_hallazgo_url_ejecucion_unica')],
            },
        ),
    ]
