# Generated by Django 6.0.6 on 2026-07-10 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('gratuito', 'Plan Gratuito'), ('estudiantil', 'Plan Estudiantil'), ('profesional', 'Plan Profesional'), ('consultora', 'Plan Consultora'), ('empresarial', 'Plan Empresarial')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('dispositivos', models.PositiveSmallIntegerField(default=1)),
                ('dispositivos_variables', models.BooleanField(default=False)),
                ('beneficios', models.JSONField(blank=True, default=list)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=160)),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro'), ('sin_especificar', 'Prefiero no decirlo')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('canal_contacto', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'Tik-Tok'), ('radio', 'Radio'), ('asesor', 'Asesor Empresarial'), ('otro', 'Otro')], help_text='Por qué medio se enteró del sistema Consultor Jurídico.', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_o_razon_social', models.CharField(max_length=160)),
                ('tipo_documento', models.CharField(choices=[('ci', 'Cédula de Identidad'), ('nit', 'NIT')], max_length=5)),
                ('numero_documento', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_facturacion', to='suscripciones.cliente')),
            ],
            options={
                'verbose_name': 'datos de facturación',
                'verbose_name_plural': 'datos de facturación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=12)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispositivos', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente_pago', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.cliente')),
                ('datos_facturacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='suscripciones.datosfacturacion')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.plan')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('libelula', 'Libélula (QR, tarjeta, banca en línea)')], default='libelula', max_length=20)),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='BOB', max_length=3)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('expirado', 'Expirado'), ('error', 'Error')], db_index=True, default='pendiente', max_length=12)),
                ('id_transaccion', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('url_pasarela', models.URLField(blank=True, default='', max_length=500)),
                ('qr_simple_url', models.URLField(blank=True, default='', max_length=500)),
                ('codigo_recaudacion', models.CharField(blank=True, default='', max_length=40)),
                ('forma_pago', models.CharField(blank=True, default='', max_length=80)),
                ('factura_numero', models.CharField(blank=True, default='', max_length=40)),
                ('factura_url', models.URLField(blank=True, default='', max_length=500)),
                ('confirmacion', models.JSONField(blank=True, null=True)),
                ('error_detalle', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='suscripciones.suscripcion')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PrecioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=12)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='suscripciones.plan')),
            ],
            options={
                'verbose_name': 'precio de plan',
                'verbose_name_plural': 'precios de planes',
                'ordering': ['plan', 'periodicidad'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'periodicidad'), name='unique_precio_plan_periodicidad')],
            },
        ),
    ]
