# Generated by Django 6.0.6 on 2026-07-10 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_planes_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_inicial', models.CharField(blank=True, default='', max_length=40)),
                ('estado', models.CharField(choices=[('libre', 'Libre (pendiente del primer ingreso)'), ('vinculada', 'Vinculada a un dispositivo'), ('bloqueada', 'Bloqueada')], db_index=True, default='libre', max_length=12)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('device_user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('vinculada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='suscripciones.suscripcion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credencial de acceso',
                'verbose_name_plural': 'credenciales de acceso',
                'ordering': ['suscripcion', 'id'],
            },
        ),
    ]
