"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'apps.cuentas.apps.CuentasConfig',
    'apps.catalogos.apps.CatalogosConfig',
    'apps.fuentes.apps.FuentesConfig',
    'apps.normativa.apps.NormativaConfig',
    'apps.modificador.apps.ModificadorConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv(
    'CELERY_RESULT_BACKEND',
    'redis://127.0.0.1:6379/1',
)
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '2100'))
CELERY_TASK_SOFT_TIME_LIMIT = int(
    os.getenv('CELERY_TASK_SOFT_TIME_LIMIT', '2000')
)
CELERY_TASK_ALWAYS_EAGER = (
    os.getenv('CELERY_TASK_ALWAYS_EAGER', 'False').lower() == 'true'
)
CELERY_TIMEZONE = 'America/La_Paz'
CELERY_BEAT_SCHEDULE = {
    'revisar-fuentes-programadas': {
        'task': 'fuentes.programar_descargas_pendientes',
        'schedule': float(os.getenv('SOURCE_SCHEDULER_INTERVAL_SECONDS', '1800')),
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / 'private_media'
MAX_PDF_UPLOAD_SIZE = int(
    os.getenv('MAX_PDF_UPLOAD_SIZE', str(100 * 1024 * 1024))
)
SOURCE_MAX_LISTING_BYTES = int(
    os.getenv('SOURCE_MAX_LISTING_BYTES', str(5 * 1024 * 1024))
)
PDF_MIN_TEXT_CHARS_PER_PAGE = int(
    os.getenv('PDF_MIN_TEXT_CHARS_PER_PAGE', '30')
)
PDF_SCANNED_IMAGE_COVERAGE = float(
    os.getenv('PDF_SCANNED_IMAGE_COVERAGE', '0.80')
)
PDF_WORD_IMAGE_DPI = int(os.getenv('PDF_WORD_IMAGE_DPI', '300'))
OCR_LANGUAGE = os.getenv('OCR_LANGUAGE', 'spa')
OCRMYPDF_COMMAND = os.getenv('OCRMYPDF_COMMAND', 'ocrmypdf')
OCR_PROCESS_TIMEOUT = int(os.getenv('OCR_PROCESS_TIMEOUT', '1800'))
OCR_CONFIDENCE_DPI = int(os.getenv('OCR_CONFIDENCE_DPI', '150'))
QUALITY_MIN_TEXT_CHARS = int(os.getenv('QUALITY_MIN_TEXT_CHARS', '200'))
QUALITY_MIN_OCR_CONFIDENCE = float(
    os.getenv('QUALITY_MIN_OCR_CONFIDENCE', '75')
)
QUALITY_MIN_EXTRACTION_CONFIDENCE = float(
    os.getenv('QUALITY_MIN_EXTRACTION_CONFIDENCE', '70')
)
_final_normativa_root = os.getenv('FINAL_NORMATIVA_ROOT', '').strip()
FINAL_NORMATIVA_ROOT = (
    Path(_final_normativa_root)
    if _final_normativa_root
    else BASE_DIR / 'NORMATIVA EMITIDA'
)
_normativa_actualizada_root = os.getenv('NORMATIVA_ACTUALIZADA_ROOT', '').strip()
NORMATIVA_ACTUALIZADA_ROOT = (
    Path(_normativa_actualizada_root)
    if _normativa_actualizada_root
    else BASE_DIR / 'NORMATIVA ACTUALIZADA'
)
FINAL_FILENAME_MAX_LENGTH = int(
    os.getenv('FINAL_FILENAME_MAX_LENGTH', '230')
)
FINAL_PATH_MAX_LENGTH = int(
    os.getenv('FINAL_PATH_MAX_LENGTH', '240')
)
FINAL_STORAGE_ROOT_LENGTH_BUDGET = int(
    os.getenv('FINAL_STORAGE_ROOT_LENGTH_BUDGET', '100')
)

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': (
        'rest_framework.pagination.PageNumberPagination'
    ),
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_RATES': {
        'login': os.getenv('LOGIN_THROTTLE_RATE', '10/min'),
    },
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('JWT_ACCESS_MINUTES', '60'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('JWT_REFRESH_DAYS', '7'))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'UPDATE_LAST_LOGIN': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Sistema Consultor Jurídico API',
    'VERSION': '1.0.0',
    'ENUM_NAME_OVERRIDES': {
        'DocumentoEstadoEnum': 'apps.normativa.models.Documento.Estado',
        'EjecucionFuenteEstadoEnum': (
            'apps.fuentes.models.EjecucionFuente.Estado'
        ),
    },
}

ALLOW_PRIVATE_SOURCE_URLS = (
    os.getenv('ALLOW_PRIVATE_SOURCE_URLS', 'False').lower() == 'true'
)
