# Generated by Django 6.0.6 on 2026-06-30 21:18

from django.db import migrations


MATERIAS = (
    ('TRIB', 'Derecho Tributario'),
    ('LAB', 'Derecho Laboral'),
    ('ADU', 'Derecho Aduanero'),
    ('ADM', 'Derecho Administrativo'),
    ('CIV', 'Derecho Civil'),
    ('PEN', 'Derecho Penal'),
    ('CONST', 'Derecho Constitucional'),
)

TIPOS_NORMA = (
    ('SC', 'Sentencia Constitucional'),
    ('DC', 'Declaración Constitucional'),
    ('AC', 'Auto Constitucional'),
    ('AS', 'Auto Supremo'),
    ('L', 'Ley'),
    ('DL', 'Decreto Ley'),
    ('DS', 'Decreto Supremo'),
    ('RS', 'Resolución Suprema'),
    ('RM', 'Resolución Ministerial'),
    ('RA', 'Resolución Administrativa'),
    ('RND', 'Resolución Normativa de Directorio'),
    ('RARA', 'Resolución de Recurso de Alzada'),
    ('RARR', 'Resolución de Recurso de Revocatoria'),
    ('RARJ', 'Resolución de Recurso Jerárquico'),
    ('RRDL', 'Resolución de Restitución de Derechos Laborales'),
)

EFECTOS_NORMATIVOS = (
    ('O', 'Originaria'),
    ('A', 'Abrogatoria'),
    ('D', 'Derogatoria'),
)

ENTIDADES_EMISORAS = (
    ('ALP', 'Asamblea Legislativa Plurinacional'),
    ('OE', 'Órgano Ejecutivo'),
    ('SIN', 'Servicio de Impuestos Nacionales'),
    ('AN', 'Aduana Nacional'),
    ('TCP', 'Tribunal Constitucional Plurinacional'),
    ('TSJ', 'Tribunal Supremo de Justicia'),
)


def cargar_catalogos(apps, schema_editor):
    modelos_con_codigo = (
        ('Materia', MATERIAS),
        ('TipoNorma', TIPOS_NORMA),
        ('EfectoNormativo', EFECTOS_NORMATIVOS),
    )
    for nombre_modelo, registros in modelos_con_codigo:
        modelo = apps.get_model('catalogos', nombre_modelo)
        for codigo, nombre in registros:
            modelo.objects.update_or_create(
                codigo=codigo,
                defaults={
                    'nombre': nombre,
                    'descripcion': '',
                    'activo': True,
                },
            )

    entidad_emisora = apps.get_model('catalogos', 'EntidadEmisora')
    for sigla, nombre in ENTIDADES_EMISORAS:
        entidad_emisora.objects.update_or_create(
            sigla=sigla,
            defaults={
                'nombre': nombre,
                'descripcion': '',
                'sitio_web': '',
                'activo': True,
            },
        )


def eliminar_catalogos(apps, schema_editor):
    modelos_con_codigo = (
        ('Materia', MATERIAS),
        ('TipoNorma', TIPOS_NORMA),
        ('EfectoNormativo', EFECTOS_NORMATIVOS),
    )
    for nombre_modelo, registros in modelos_con_codigo:
        modelo = apps.get_model('catalogos', nombre_modelo)
        modelo.objects.filter(
            codigo__in=[codigo for codigo, _ in registros]
        ).delete()

    entidad_emisora = apps.get_model('catalogos', 'EntidadEmisora')
    entidad_emisora.objects.filter(
        sigla__in=[sigla for sigla, _ in ENTIDADES_EMISORAS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_catalogos, eliminar_catalogos),
    ]
