# Generated by Django 6.0.6 on 2026-06-30 21:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EfectoNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'efecto normativo',
                'verbose_name_plural': 'efectos normativos',
                'ordering': ('nombre',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='catalogos_efecto_nombre_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='EntidadEmisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('sitio_web', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'entidad emisora',
                'verbose_name_plural': 'entidades emisoras',
                'ordering': ('nombre',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='catalogos_entidad_nombre_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materias',
                'ordering': ('nombre',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='catalogos_materia_nombre_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='TipoNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'tipo de norma',
                'verbose_name_plural': 'tipos de norma',
                'ordering': ('nombre',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='catalogos_tiponorma_nombre_ci_unique')],
            },
        ),
    ]
