# Generated by Django 6.0.6 on 2026-07-01 02:19

import apps.catalogos.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_cargar_catalogos_iniciales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='efectonormativo',
            options={'ordering': ('orden', 'nombre'), 'verbose_name': 'efecto normativo', 'verbose_name_plural': 'efectos normativos'},
        ),
        migrations.AlterModelOptions(
            name='entidademisora',
            options={'ordering': ('orden', 'nombre'), 'verbose_name': 'entidad emisora', 'verbose_name_plural': 'entidades emisoras'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ('orden', 'nombre'), 'verbose_name': 'materia', 'verbose_name_plural': 'materias'},
        ),
        migrations.AlterModelOptions(
            name='tiponorma',
            options={'ordering': ('orden', 'nombre'), 'verbose_name': 'tipo de norma', 'verbose_name_plural': 'tipos de norma'},
        ),
        migrations.AddField(
            model_name='efectonormativo',
            name='abreviatura_archivo',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='efectonormativo',
            name='es_efecto_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='efectonormativo',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entidademisora',
            name='codigo',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[apps.catalogos.validators.validar_codigo_catalogo]),
        ),
        migrations.AddField(
            model_name='entidademisora',
            name='nivel',
            field=models.CharField(blank=True, default='NACIONAL', max_length=30),
        ),
        migrations.AddField(
            model_name='entidademisora',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entidademisora',
            name='tipo_entidad',
            field=models.CharField(choices=[('LEGISLATIVO', 'Legislativo'), ('EJECUTIVO', 'Ejecutivo'), ('JUDICIAL', 'Judicial'), ('CONSTITUCIONAL', 'Constitucional'), ('TRIBUTARIO', 'Tributario'), ('ADUANERO', 'Aduanero'), ('MINISTERIAL', 'Ministerial'), ('MUNICIPAL', 'Municipal'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
        migrations.AddField(
            model_name='materia',
            name='carpeta_destino',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[apps.catalogos.validators.validar_carpeta_destino]),
        ),
        migrations.AddField(
            model_name='materia',
            name='color_etiqueta',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='materia',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materia',
            name='requiere_revision',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tiponorma',
            name='abreviatura_archivo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tiponorma',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiponorma',
            name='requiere_fecha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tiponorma',
            name='requiere_numero',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='efectonormativo',
            name='codigo',
            field=models.CharField(max_length=1, unique=True, validators=[apps.catalogos.validators.validar_codigo_efecto]),
        ),
        migrations.AlterField(
            model_name='entidademisora',
            name='sigla',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=30, unique=True, validators=[apps.catalogos.validators.validar_codigo_catalogo]),
        ),
        migrations.AlterField(
            model_name='tiponorma',
            name='codigo',
            field=models.CharField(max_length=30, unique=True, validators=[apps.catalogos.validators.validar_codigo_catalogo]),
        ),
        migrations.CreateModel(
            name='PalabraClaveMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_clave', models.CharField(max_length=150)),
                ('peso', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palabras_clave_deteccion', to='catalogos.materia')),
            ],
            options={
                'verbose_name': 'palabra clave de materia',
                'verbose_name_plural': 'palabras clave de materia',
                'ordering': ('-peso', 'palabra_clave'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('palabra_clave'), models.F('materia'), name='catalogos_palabra_materia_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='PatronTipoNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_regex', models.TextField(validators=[apps.catalogos.validators.validar_regex])),
                ('ejemplo_texto', models.CharField(blank=True, default='', max_length=250)),
                ('prioridad', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_norma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrones_deteccion', to='catalogos.tiponorma')),
            ],
            options={
                'verbose_name': 'patrón de tipo de norma',
                'verbose_name_plural': 'patrones de tipo de norma',
                'ordering': ('prioridad', 'id'),
                'constraints': [models.UniqueConstraint(fields=('tipo_norma', 'patron_regex'), name='catalogos_patron_tipo_regex_unique')],
            },
        ),
        migrations.CreateModel(
            name='ReglaEfectoNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expresion', models.CharField(max_length=250)),
                ('prioridad', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('efecto_normativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_deteccion', to='catalogos.efectonormativo')),
            ],
            options={
                'verbose_name': 'regla de efecto normativo',
                'verbose_name_plural': 'reglas de efecto normativo',
                'ordering': ('prioridad', 'expresion'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('expresion'), models.F('efecto_normativo'), name='catalogos_regla_efecto_ci_unique')],
            },
        ),
    ]
