# Generated by Django 6.0.6 on 2026-07-01 02:20

import apps.catalogos.validators
from django.db import migrations, models
from django.utils.text import slugify


def completar_valores_personalizados(apps, schema_editor):
    TipoNorma = apps.get_model('catalogos', 'TipoNorma')
    EfectoNormativo = apps.get_model('catalogos', 'EfectoNormativo')
    Materia = apps.get_model('catalogos', 'Materia')
    EntidadEmisora = apps.get_model('catalogos', 'EntidadEmisora')

    for tipo in TipoNorma.objects.filter(abreviatura_archivo=''):
        tipo.abreviatura_archivo = tipo.codigo[:10]
        tipo.save(update_fields=('abreviatura_archivo',))
    for efecto in EfectoNormativo.objects.filter(abreviatura_archivo=''):
        efecto.abreviatura_archivo = efecto.codigo[:1]
        efecto.save(update_fields=('abreviatura_archivo',))
    for materia in Materia.objects.filter(slug__isnull=True):
        slug_base = slugify(materia.nombre) or f'materia-{materia.pk}'
        slug = slug_base
        if Materia.objects.filter(slug=slug).exclude(pk=materia.pk).exists():
            slug = f'{slug_base}-{materia.pk}'
        materia.slug = slug
        materia.save(update_fields=('slug',))
    for materia in Materia.objects.filter(carpeta_destino__isnull=True):
        carpeta = materia.nombre
        if Materia.objects.filter(carpeta_destino=carpeta).exclude(pk=materia.pk).exists():
            carpeta = f'{materia.nombre} {materia.pk}'
        materia.carpeta_destino = carpeta
        materia.save(update_fields=('carpeta_destino',))
    for entidad in EntidadEmisora.objects.filter(codigo__isnull=True):
        entidad.codigo = entidad.sigla
        entidad.save(update_fields=('codigo',))


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_completar_catalogos'),
    ]

    operations = [
        migrations.RunPython(
            completar_valores_personalizados,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='efectonormativo',
            name='abreviatura_archivo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='entidademisora',
            name='codigo',
            field=models.CharField(max_length=30, unique=True, validators=[apps.catalogos.validators.validar_codigo_catalogo]),
        ),
        migrations.AlterField(
            model_name='materia',
            name='carpeta_destino',
            field=models.CharField(max_length=100, unique=True, validators=[apps.catalogos.validators.validar_carpeta_destino]),
        ),
        migrations.AlterField(
            model_name='materia',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tiponorma',
            name='abreviatura_archivo',
            field=models.CharField(max_length=10),
        ),
    ]
