# Generated by Django 6.0.5 on 2026-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leyresultado',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Visible en procesos activos'),
        ),
        migrations.AlterField(
            model_name='leyoriginal',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('abrogada', 'Abrogada')], db_index=True, default='activo', max_length=16),
        ),
    ]
