# Generated by Django 6.0.6 on 2026-07-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_perfilusuario_bio_perfilusuario_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
