import {
  efectoNormativoSchema,
  entidadEmisoraSchema,
  materiaSchema,
  palabraClaveMateriaSchema,
  patronTipoNormaSchema,
  reglaEfectoNormativoSchema,
  tipoNormaSchema,
} from "./schemas/catalogos-schemas";
import type { CatalogoDefinition, CatalogoDefinitionKey, SelectOption } from "./types/catalogos.types";

const tipoEntidadOptions: SelectOption[] = [
  ["LEGISLATIVO", "Legislativo"],
  ["EJECUTIVO", "Ejecutivo"],
  ["JUDICIAL", "Judicial"],
  ["CONSTITUCIONAL", "Constitucional"],
  ["TRIBUTARIO", "Tributario"],
  ["ADUANERO", "Aduanero"],
  ["MINISTERIAL", "Ministerial"],
  ["MUNICIPAL", "Municipal"],
  ["OTRO", "Otro"],
].map(([value, label]) => ({ value, label }));

export const catalogoDefinitions: Record<CatalogoDefinitionKey, CatalogoDefinition> = {
  "tipos-norma": {
    key: "tipos-norma",
    endpoint: "catalogos/tipos-norma",
    title: "Tipos de norma",
    singular: "tipo de norma",
    description: "Gestiona leyes, decretos, resoluciones y su nomenclatura de archivo.",
    ordering: "orden",
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nombre", label: "Nombre" },
      { key: "abreviatura_archivo", label: "Abreviatura" },
      { key: "requiere_numero", label: "Requiere número", kind: "boolean" },
      { key: "requiere_fecha", label: "Requiere fecha", kind: "boolean" },
      { key: "activo", label: "Estado", kind: "status" },
      { key: "updated_at", label: "Actualizado", kind: "date" },
    ],
    fields: [
      { name: "codigo", label: "Código", type: "text", placeholder: "Ej. DS", maxLength: 30 },
      { name: "nombre", label: "Nombre", type: "text", maxLength: 150 },
      { name: "descripcion", label: "Descripción", type: "textarea", className: "sm:col-span-2" },
      { name: "abreviatura_archivo", label: "Abreviatura para archivo", type: "text", maxLength: 10 },
      { name: "orden", label: "Orden", type: "number" },
      { name: "requiere_numero", label: "Requiere número", type: "switch" },
      { name: "requiere_fecha", label: "Requiere fecha", type: "switch" },
      { name: "activo", label: "Estado activo", type: "switch" },
    ],
    schema: tipoNormaSchema,
    defaultValues: {
      codigo: "",
      nombre: "",
      descripcion: "",
      abreviatura_archivo: "",
      requiere_numero: true,
      requiere_fecha: true,
      orden: 0,
      activo: true,
    },
    successCreated: "Tipo de norma creado correctamente.",
    successUpdated: "Tipo de norma actualizado correctamente.",
  },
  "efectos-normativos": {
    key: "efectos-normativos",
    endpoint: "catalogos/efectos-normativos",
    title: "Efectos normativos",
    singular: "efecto normativo",
    description: "Define si una norma es originaria, abrogatoria o derogatoria.",
    ordering: "orden",
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nombre", label: "Nombre" },
      { key: "abreviatura_archivo", label: "Abreviatura" },
      { key: "descripcion", label: "Descripción" },
      { key: "activo", label: "Estado", kind: "status" },
      { key: "updated_at", label: "Actualizado", kind: "date" },
    ],
    fields: [
      { name: "codigo", label: "Código", type: "text", placeholder: "O, A o D", maxLength: 1 },
      { name: "nombre", label: "Nombre", type: "text" },
      { name: "abreviatura_archivo", label: "Abreviatura", type: "text", maxLength: 1 },
      { name: "orden", label: "Orden", type: "number" },
      { name: "descripcion", label: "Descripción", type: "textarea", className: "sm:col-span-2" },
      { name: "es_efecto_final", label: "Es efecto final", type: "switch" },
      { name: "activo", label: "Estado activo", type: "switch" },
    ],
    schema: efectoNormativoSchema,
    defaultValues: {
      codigo: "",
      nombre: "",
      abreviatura_archivo: "",
      descripcion: "",
      orden: 0,
      es_efecto_final: false,
      activo: true,
    },
    successCreated: "Efecto normativo creado correctamente.",
    successUpdated: "Efecto normativo actualizado correctamente.",
  },
  materias: {
    key: "materias",
    endpoint: "catalogos/materias",
    title: "Materias jurídicas",
    singular: "materia",
    description: "Configura la clasificación jurídica y su subcarpeta de destino.",
    ordering: "orden",
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nombre", label: "Nombre" },
      { key: "slug", label: "Slug" },
      { key: "carpeta_destino", label: "Carpeta destino" },
      { key: "requiere_revision", label: "Revisión requerida", kind: "boolean" },
      { key: "activo", label: "Estado", kind: "status" },
      { key: "updated_at", label: "Actualizado", kind: "date" },
    ],
    fields: [
      { name: "codigo", label: "Código", type: "text", placeholder: "Ej. TRIBUTARIO" },
      { name: "nombre", label: "Nombre", type: "text" },
      { name: "descripcion", label: "Descripción", type: "textarea", className: "sm:col-span-2" },
      { name: "slug", label: "Slug", type: "text", placeholder: "derecho-tributario" },
      {
        name: "carpeta_destino",
        label: "Carpeta destino",
        type: "text",
        placeholder: "Derecho Tributario",
        help: "Esta será la subcarpeta dentro de NORMATIVA EMITIDA. No escriba rutas completas ni caracteres especiales.",
      },
      { name: "color_etiqueta", label: "Color de etiqueta", type: "text", placeholder: "#0ea5e9" },
      { name: "orden", label: "Orden", type: "number" },
      { name: "requiere_revision", label: "Requiere revisión", type: "switch" },
      { name: "activo", label: "Estado activo", type: "switch" },
    ],
    schema: materiaSchema,
    defaultValues: {
      codigo: "",
      nombre: "",
      descripcion: "",
      slug: "",
      carpeta_destino: "",
      color_etiqueta: "",
      requiere_revision: true,
      orden: 0,
      activo: true,
    },
    successCreated: "Materia creada correctamente.",
    successUpdated: "Materia actualizada correctamente.",
  },
  "entidades-emisoras": {
    key: "entidades-emisoras",
    endpoint: "catalogos/entidades-emisoras",
    title: "Entidades emisoras",
    singular: "entidad emisora",
    description: "Administra las instituciones responsables de emitir normativa.",
    ordering: "orden",
    columns: [
      { key: "codigo", label: "Código" },
      { key: "sigla", label: "Sigla" },
      { key: "nombre", label: "Nombre" },
      { key: "tipo_entidad", label: "Tipo" },
      { key: "nivel", label: "Nivel" },
      { key: "sitio_web", label: "Sitio web", kind: "link" },
      { key: "activo", label: "Estado", kind: "status" },
      { key: "updated_at", label: "Actualizado", kind: "date" },
    ],
    fields: [
      { name: "codigo", label: "Código", type: "text", placeholder: "Ej. SIN" },
      { name: "sigla", label: "Sigla", type: "text", placeholder: "Ej. SIN" },
      { name: "nombre", label: "Nombre", type: "text", className: "sm:col-span-2" },
      { name: "tipo_entidad", label: "Tipo de entidad", type: "select", options: tipoEntidadOptions },
      { name: "nivel", label: "Nivel", type: "text", placeholder: "NACIONAL" },
      { name: "sitio_web", label: "Sitio web oficial", type: "text", placeholder: "https://..." },
      { name: "orden", label: "Orden", type: "number" },
      { name: "descripcion", label: "Descripción", type: "textarea", className: "sm:col-span-2" },
      { name: "activo", label: "Estado activo", type: "switch" },
    ],
    schema: entidadEmisoraSchema,
    defaultValues: {
      codigo: "",
      sigla: "",
      nombre: "",
      tipo_entidad: "OTRO",
      nivel: "NACIONAL",
      sitio_web: "",
      descripcion: "",
      orden: 0,
      activo: true,
    },
    successCreated: "Entidad emisora creada correctamente.",
    successUpdated: "Entidad emisora actualizada correctamente.",
  },
  "patrones-tipo-norma": {
    key: "patrones-tipo-norma",
    endpoint: "catalogos/patrones-tipo-norma",
    title: "Patrones de tipo de norma",
    singular: "patrón de tipo de norma",
    description: "Expresiones regulares para reconocer tipos de norma.",
    ordering: "prioridad",
    columns: [
      { key: "tipo_norma_nombre", label: "Tipo de norma" },
      { key: "patron_regex", label: "Patrón regex" },
      { key: "ejemplo_texto", label: "Ejemplo" },
      { key: "prioridad", label: "Prioridad" },
      { key: "activo", label: "Estado", kind: "status" },
      { key: "updated_at", label: "Actualizado", kind: "date" },
    ],
    fields: [
      { name: "tipo_norma", label: "Tipo de norma", type: "relation", relationDefinition: "tipos-norma" },
      { name: "prioridad", label: "Prioridad", type: "number" },
      { name: "patron_regex", label: "Patrón regex", type: "textarea", className: "sm:col-span-2" },
      { name: "ejemplo_texto", label: "Ejemplo de texto", type: "text", className: "sm:col-span-2" },
      { name: "activo", label: "Estado activo", type: "switch" },
    ],
    schema: patronTipoNormaSchema,
    defaultValues: { tipo_norma: 0, patron_regex: "", ejemplo_texto: "", prioridad: 0, activo: true },
    successCreated: "Patrón creado correctamente.",
    successUpdated: "Patrón actualizado correctamente.",
  },
  "palabras-clave-materia": {
    key: "palabras-clave-materia",
    endpoint: "catalogos/palabras-clave-materia",
    title: "Palabras clave de materia",
    singular: "palabra clave",
    description: "Términos ponderados para sugerir una materia jurídica.",
    ordering: "-peso",
    columns: [
      { key: "materia_nombre", label: "Materia" },
      { key: "palabra_clave", label: "Palabra clave" },
      { key: "peso", label: "Peso" },
      { key: "activo", label: "Estado", kind: "status" },
      { key: "updated_at", label: "Actualizado", kind: "date" },
    ],
    fields: [
      { name: "materia", label: "Materia", type: "relation", relationDefinition: "materias" },
      { name: "palabra_clave", label: "Palabra clave", type: "text" },
      { name: "peso", label: "Peso", type: "number" },
      { name: "activo", label: "Estado activo", type: "switch" },
    ],
    schema: palabraClaveMateriaSchema,
    defaultValues: { materia: 0, palabra_clave: "", peso: 10, activo: true },
    successCreated: "Palabra clave creada correctamente.",
    successUpdated: "Palabra clave actualizada correctamente.",
  },
  "reglas-efecto-normativo": {
    key: "reglas-efecto-normativo",
    endpoint: "catalogos/reglas-efecto-normativo",
    title: "Reglas de efecto normativo",
    singular: "regla de efecto normativo",
    description: "Expresiones para detectar abrogaciones y derogaciones.",
    ordering: "prioridad",
    columns: [
      { key: "efecto_normativo_nombre", label: "Efecto" },
      { key: "expresion", label: "Expresión" },
      { key: "prioridad", label: "Prioridad" },
      { key: "activo", label: "Estado", kind: "status" },
      { key: "updated_at", label: "Actualizado", kind: "date" },
    ],
    fields: [
      {
        name: "efecto_normativo",
        label: "Efecto normativo",
        type: "relation",
        relationDefinition: "efectos-normativos",
      },
      { name: "expresion", label: "Expresión", type: "text" },
      { name: "prioridad", label: "Prioridad", type: "number" },
      { name: "activo", label: "Estado activo", type: "switch" },
    ],
    schema: reglaEfectoNormativoSchema,
    defaultValues: { efecto_normativo: 0, expresion: "", prioridad: 0, activo: true },
    successCreated: "Regla creada correctamente.",
    successUpdated: "Regla actualizada correctamente.",
  },
};
