# Generated by Django 6.0.6 on 2026-07-08 04:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeyOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ley', models.CharField(db_index=True, max_length=32, verbose_name='Código de ley')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('contenido_completo', models.TextField(verbose_name='Contenido completo')),
                ('archivo_origen', models.CharField(blank=True, max_length=255, verbose_name='Archivo origen')),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de carga')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('abrogada', 'Abrogada')], db_index=True, default='activo', max_length=16)),
                ('estado_proceso', models.CharField(choices=[('pendiente', 'Pendiente de modificación'), ('vinculada', 'Modificación vinculada'), ('modificada', 'Modificada')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Ley original',
                'verbose_name_plural': 'Leyes originales',
                'ordering': ['codigo_ley'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('codigo_ley',), name='modificador_uniq_ley_activa_por_codigo')],
            },
        ),
        migrations.CreateModel(
            name='ModificacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_origen', models.CharField(max_length=255, verbose_name='Archivo origen')),
                ('contenido', models.TextField(verbose_name='Contenido del documento')),
                ('codigo_ley_detectado', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Código detectado')),
                ('palabras_clave_detectadas', models.CharField(blank=True, max_length=255, verbose_name='Palabras clave')),
                ('procesado', models.BooleanField(db_index=True, default=False)),
                ('estado_vinculacion', models.CharField(choices=[('pendiente', 'Ley no vinculada'), ('vinculada', 'Vinculada — Lista para procesar'), ('procesado', 'Procesado exitosamente')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('ley_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones', to='modificador.leyoriginal')),
            ],
            options={
                'verbose_name': 'Modificación',
                'verbose_name_plural': 'Modificaciones',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='LeyResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_final', models.TextField(verbose_name='Contenido final')),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('es_version_final', models.BooleanField(default=False, verbose_name='Versión final aprobada')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Visible en procesos activos')),
                ('notas', models.CharField(blank=True, max_length=500)),
                ('preinforme', models.JSONField(blank=True, default=dict, verbose_name='Pre-informe de auditoría')),
                ('archivo_docx', models.CharField(blank=True, max_length=500, verbose_name='Ruta Word generado')),
                ('archivo_pdf', models.CharField(blank=True, max_length=500, verbose_name='Ruta PDF generado')),
                ('ley_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='modificador.leyoriginal')),
            ],
            options={
                'verbose_name': 'Ley resultado',
                'verbose_name_plural': 'Leyes resultado',
                'ordering': ['-fecha_modificacion'],
                'constraints': [models.UniqueConstraint(fields=('ley_original', 'version'), name='modificador_uniq_resultado_version')],
            },
        ),
    ]
