# Generated by Django 6.0.6 on 2026-07-01 05:30

import apps.normativa.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0007_limpiar_metadatos_documentos'),
        ('fuentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('titulo', models.CharField(max_length=500)),
                ('objeto', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('nomenclatura_preliminar', models.CharField(blank=True, default='', editable=False, max_length=1000)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_PROCESAMIENTO', 'Pendiente de procesamiento'), ('PROCESANDO', 'Procesando'), ('PENDIENTE_REVISION', 'Pendiente de revisión'), ('VALIDADO', 'Validado'), ('ERROR', 'Error'), ('RECHAZADO', 'Rechazado')], db_index=True, default='BORRADOR', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eliminado_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_normativos_creados', to=settings.AUTH_USER_MODEL)),
                ('efecto_normativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_normativos', to='catalogos.efectonormativo')),
                ('entidad_emisora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_normativos', to='catalogos.entidademisora')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_normativos', to='catalogos.materia')),
                ('tipo_norma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_normativos', to='catalogos.tiponorma')),
            ],
            options={
                'verbose_name': 'documento normativo',
                'verbose_name_plural': 'documentos normativos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ArchivoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('PDF_ORIGINAL', 'PDF original'), ('PDF_OCR', 'PDF con OCR'), ('WORD', 'Documento Word')], default='PDF_ORIGINAL', max_length=20)),
                ('archivo', models.FileField(max_length=500, upload_to=apps.normativa.models.archivo_documento_path)),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('tamano_bytes', models.PositiveBigIntegerField()),
                ('hash_sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_normativos_creados', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='normativa.documento')),
            ],
            options={
                'verbose_name': 'archivo de documento',
                'verbose_name_plural': 'archivos de documentos',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'Documento creado'), ('EDITADO', 'Documento editado'), ('ARCHIVO_CARGADO', 'Archivo cargado'), ('ENVIADO_PROCESAMIENTO', 'Enviado a procesamiento'), ('ESTADO_CAMBIADO', 'Estado cambiado'), ('RECHAZADO', 'Documento rechazado')], max_length=30)),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, default='', max_length=30)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='normativa.documento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_documentos_normativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de documento',
                'verbose_name_plural': 'historiales de documentos',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrigenDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_origen', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='normativa.documento')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_normativos', to='fuentes.fuenteweb')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_normativos', to='fuentes.fuenteseccion')),
            ],
            options={
                'verbose_name': 'origen de documento',
                'verbose_name_plural': 'orígenes de documentos',
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['estado', '-created_at'], name='normativa_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo_norma', 'numero'], name='normativa_tipo_numero_idx'),
        ),
        migrations.AddConstraint(
            model_name='archivodocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'tipo_archivo'), name='normativa_un_archivo_por_tipo'),
        ),
        migrations.AddConstraint(
            model_name='archivodocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_archivo', 'PDF_ORIGINAL')), fields=('hash_sha256',), name='normativa_pdf_original_hash_unique'),
        ),
    ]
