# Generated by Django 6.0.6 on 2026-07-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0003_normalizar_avance_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivodocumento',
            name='tipo_archivo',
            field=models.CharField(choices=[('PDF_ORIGINAL', 'PDF original'), ('PDF_PROCESADO', 'PDF procesado'), ('PDF_OCR', 'PDF con OCR (legado)'), ('WORD', 'Documento Word')], default='PDF_ORIGINAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_PROCESAMIENTO', 'Pendiente de procesamiento'), ('PROCESANDO', 'Procesando'), ('PENDIENTE_EXTRACCION', 'Pendiente de extracción jurídica'), ('PENDIENTE_REVISION', 'Pendiente de revisión'), ('VALIDADO', 'Validado'), ('ERROR', 'Error'), ('DESCARTADO', 'Descartado')], db_index=True, default='PENDIENTE_PROCESAMIENTO', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialdocumento',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Documento creado'), ('EDITADO', 'Documento editado'), ('ARCHIVO_CARGADO', 'Archivo cargado'), ('ENVIADO_PROCESAMIENTO', 'Enviado a procesamiento'), ('ESTADO_CAMBIADO', 'Estado cambiado'), ('PROCESAMIENTO_INICIADO', 'Procesamiento iniciado'), ('PROCESAMIENTO_COMPLETADO', 'Procesamiento completado'), ('PROCESAMIENTO_ERROR', 'Error de procesamiento'), ('DESCARTADO', 'Documento descartado')], max_length=30),
        ),
        migrations.CreateModel(
            name='ResultadoProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_COLA', 'En cola'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], db_index=True, default='EN_COLA', max_length=20)),
                ('tipo_pdf', models.CharField(choices=[('TEXTO', 'PDF con texto'), ('ESCANEADO', 'PDF escaneado'), ('MIXTO', 'PDF mixto'), ('DESCONOCIDO', 'Sin determinar')], default='DESCONOCIDO', max_length=20)),
                ('tarea_id', models.CharField(blank=True, default='', max_length=255)),
                ('numero_paginas', models.PositiveIntegerField(default=0)),
                ('paginas_con_texto', models.PositiveIntegerField(default=0)),
                ('paginas_con_ocr', models.PositiveIntegerField(default=0)),
                ('requirio_ocr', models.BooleanField(default=False)),
                ('ocr_aplicado', models.BooleanField(default=False)),
                ('confianza_ocr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('caracteres_extraidos', models.PositiveBigIntegerField(default=0)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('iniciado_at', models.DateTimeField(blank=True, null=True)),
                ('finalizado_at', models.DateTimeField(blank=True, null=True)),
                ('duracion_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error_codigo', models.CharField(blank=True, default='', max_length=60)),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('detalles_tecnicos', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_procesamiento', to='normativa.documento')),
            ],
            options={
                'verbose_name': 'resultado de procesamiento',
                'verbose_name_plural': 'resultados de procesamiento',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='TextoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.PositiveIntegerField()),
                ('metodo', models.CharField(choices=[('TEXTO_ORIGINAL', 'Texto original'), ('OCR', 'OCR')], max_length=20)),
                ('texto', models.TextField(blank=True, default='')),
                ('caracteres', models.PositiveIntegerField(default=0)),
                ('confianza_ocr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='normativa.resultadoprocesamiento')),
            ],
            options={
                'verbose_name': 'texto de página',
                'verbose_name_plural': 'textos de páginas',
                'ordering': ('numero_pagina',),
                'constraints': [models.UniqueConstraint(fields=('resultado', 'numero_pagina'), name='normativa_texto_pagina_unica')],
            },
        ),
    ]
