# Generated by Django 6.0.6 on 2026-07-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_limpiar_metadatos_documentos'),
        ('normativa', '0004_alter_archivodocumento_tipo_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdocumento',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Documento creado'), ('EDITADO', 'Documento editado'), ('ARCHIVO_CARGADO', 'Archivo cargado'), ('ENVIADO_PROCESAMIENTO', 'Enviado a procesamiento'), ('ESTADO_CAMBIADO', 'Estado cambiado'), ('PROCESAMIENTO_INICIADO', 'Procesamiento iniciado'), ('PROCESAMIENTO_COMPLETADO', 'Procesamiento completado'), ('PROCESAMIENTO_ERROR', 'Error de procesamiento'), ('EXTRACCION_INICIADA', 'Extracción jurídica iniciada'), ('EXTRACCION_COMPLETADA', 'Extracción jurídica completada'), ('EXTRACCION_ERROR', 'Error de extracción jurídica'), ('DESCARTADO', 'Documento descartado')], max_length=30),
        ),
        migrations.CreateModel(
            name='PropuestaExtraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_COLA', 'En cola'), ('EXTRAYENDO', 'Extrayendo datos'), ('COMPLETADA', 'Propuesta completada'), ('ERROR', 'Error')], db_index=True, default='EN_COLA', max_length=20)),
                ('tarea_id', models.CharField(blank=True, default='', max_length=255)),
                ('numero_propuesto', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_emision_propuesta', models.DateField(blank=True, null=True)),
                ('titulo_propuesto', models.CharField(blank=True, default='', max_length=500)),
                ('objeto_propuesto', models.TextField(blank=True, default='')),
                ('confianza_global', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('iniciado_at', models.DateTimeField(blank=True, null=True)),
                ('finalizado_at', models.DateTimeField(blank=True, null=True)),
                ('duracion_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error_codigo', models.CharField(blank=True, default='', max_length=60)),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('detalles_tecnicos', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propuesta_extraccion', to='normativa.documento')),
                ('efecto_normativo_propuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_extraccion', to='catalogos.efectonormativo')),
                ('entidad_emisora_propuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_extraccion', to='catalogos.entidademisora')),
                ('materia_propuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_extraccion', to='catalogos.materia')),
                ('tipo_norma_propuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_extraccion', to='catalogos.tiponorma')),
            ],
            options={
                'verbose_name': 'propuesta de extracción jurídica',
                'verbose_name_plural': 'propuestas de extracción jurídica',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='EvidenciaExtraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('TIPO_NORMA', 'Tipo de norma'), ('NUMERO', 'Número'), ('FECHA_EMISION', 'Fecha de emisión'), ('TITULO', 'Título'), ('OBJETO', 'Objeto'), ('EFECTO_NORMATIVO', 'Efecto normativo'), ('MATERIA', 'Materia'), ('ENTIDAD_EMISORA', 'Entidad emisora')], max_length=30)),
                ('valor_propuesto', models.TextField(blank=True, default='')),
                ('confianza', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numero_pagina', models.PositiveIntegerField(blank=True, null=True)),
                ('fragmento', models.TextField(blank=True, default='')),
                ('regla_aplicada', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='normativa.propuestaextraccion')),
            ],
            options={
                'verbose_name': 'evidencia de extracción',
                'verbose_name_plural': 'evidencias de extracción',
                'ordering': ('campo',),
                'constraints': [models.UniqueConstraint(fields=('propuesta', 'campo'), name='normativa_evidencia_campo_unica')],
            },
        ),
    ]
