# Generated by Django 6.0.6 on 2026-07-01 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0005_alter_historialdocumento_accion_propuestaextraccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento_canonico',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_duplicados', to='normativa.documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_PROCESAMIENTO', 'Pendiente de procesamiento'), ('PROCESANDO', 'Procesando'), ('PENDIENTE_EXTRACCION', 'Pendiente de extracción jurídica'), ('PENDIENTE_REVISION', 'Pendiente de revisión'), ('CONTROL_CALIDAD', 'Control de calidad'), ('LISTO_PARA_CONVERSION', 'Listo para conversión'), ('PENDIENTE_REVISION_RAPIDA', 'Pendiente de revisión rápida'), ('OBSERVADO', 'Observado'), ('DUPLICADO_CONFIRMADO', 'Duplicado confirmado'), ('VALIDADO', 'Validado'), ('ERROR', 'Error'), ('DESCARTADO', 'Descartado')], db_index=True, default='PENDIENTE_PROCESAMIENTO', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialdocumento',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Documento creado'), ('EDITADO', 'Documento editado'), ('ARCHIVO_CARGADO', 'Archivo cargado'), ('ENVIADO_PROCESAMIENTO', 'Enviado a procesamiento'), ('ESTADO_CAMBIADO', 'Estado cambiado'), ('PROCESAMIENTO_INICIADO', 'Procesamiento iniciado'), ('PROCESAMIENTO_COMPLETADO', 'Procesamiento completado'), ('PROCESAMIENTO_ERROR', 'Error de procesamiento'), ('EXTRACCION_INICIADA', 'Extracción jurídica iniciada'), ('EXTRACCION_COMPLETADA', 'Extracción jurídica completada'), ('EXTRACCION_ERROR', 'Error de extracción jurídica'), ('CALIDAD_INICIADA', 'Control de calidad iniciado'), ('CALIDAD_COMPLETADA', 'Control de calidad completado'), ('CALIDAD_ERROR', 'Error de control de calidad'), ('DUPLICADO_DETECTADO', 'Duplicado detectado'), ('DESCARTADO', 'Documento descartado')], max_length=30),
        ),
        migrations.CreateModel(
            name='EvaluacionCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_COLA', 'En cola'), ('ANALIZANDO', 'Analizando'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], db_index=True, default='EN_COLA', max_length=20)),
                ('resultado', models.CharField(blank=True, choices=[('SIN_ALERTAS_GRAVES', 'Sin alertas graves'), ('ALERTA_LEVE', 'Alerta leve'), ('ALERTA_GRAVE', 'Alerta grave'), ('DUPLICADO_CONFIRMADO', 'Duplicado confirmado')], db_index=True, default='', max_length=30)),
                ('tarea_id', models.CharField(blank=True, default='', max_length=255)),
                ('hash_contenido', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('puntuacion_calidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_alertas', models.PositiveIntegerField(default=0)),
                ('alertas_leves', models.PositiveIntegerField(default=0)),
                ('alertas_graves', models.PositiveIntegerField(default=0)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('iniciado_at', models.DateTimeField(blank=True, null=True)),
                ('finalizado_at', models.DateTimeField(blank=True, null=True)),
                ('duracion_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error_codigo', models.CharField(blank=True, default='', max_length=60)),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('metricas', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_calidad', to='normativa.documento')),
                ('documento_coincidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_coincidentes', to='normativa.documento')),
            ],
            options={
                'verbose_name': 'evaluación de calidad',
                'verbose_name_plural': 'evaluaciones de calidad',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CoincidenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HASH_IDENTICO', 'PDF idéntico'), ('MISMA_NORMA', 'Misma norma'), ('CONTENIDO_SIMILAR', 'Contenido similar'), ('IDENTIFICADOR_CONFLICTIVO', 'Identificador conflictivo')], max_length=30)),
                ('similitud_titulo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('similitud_contenido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('misma_fecha', models.BooleanField(default=False)),
                ('mismo_identificador', models.BooleanField(default=False)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento_coincidente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coincidencias_detectadas', to='normativa.documento')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias', to='normativa.evaluacioncalidad')),
            ],
            options={
                'verbose_name': 'coincidencia documental',
                'verbose_name_plural': 'coincidencias documentales',
                'ordering': ('-similitud_contenido', '-similitud_titulo'),
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'documento_coincidente', 'tipo'), name='normativa_coincidencia_tipo_unica')],
            },
        ),
        migrations.CreateModel(
            name='AlertaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('LEVE', 'Leve'), ('GRAVE', 'Grave')], max_length=15)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada')], db_index=True, default='ACTIVA', max_length=15)),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('resuelta_at', models.DateTimeField(blank=True, null=True)),
                ('nota_resolucion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_relacionadas', to='normativa.documento')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_calidad_resueltas', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='normativa.evaluacioncalidad')),
            ],
            options={
                'verbose_name': 'alerta de calidad',
                'verbose_name_plural': 'alertas de calidad',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'codigo', 'documento_relacionado'), name='normativa_alerta_codigo_documento_unica')],
            },
        ),
    ]
