# Generated by Django 6.0.6 on 2026-07-02 02:28

import apps.normativa.models
import apps.normativa.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0006_documento_documento_canonico_alter_documento_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_PROCESAMIENTO', 'Pendiente de procesamiento'), ('PROCESANDO', 'Procesando'), ('PENDIENTE_EXTRACCION', 'Pendiente de extracción jurídica'), ('PENDIENTE_REVISION', 'Pendiente de revisión'), ('CONTROL_CALIDAD', 'Control de calidad'), ('LISTO_PARA_CONVERSION', 'Listo para conversión'), ('PENDIENTE_REVISION_RAPIDA', 'Pendiente de revisión rápida'), ('OBSERVADO', 'Observado'), ('DUPLICADO_CONFIRMADO', 'Duplicado confirmado'), ('CONVIRTIENDO', 'Convirtiendo a Word'), ('ERROR_CONVERSION', 'Error de conversión'), ('FINALIZADO', 'Finalizado'), ('VALIDADO', 'Validado'), ('ERROR', 'Error'), ('DESCARTADO', 'Descartado')], db_index=True, default='PENDIENTE_PROCESAMIENTO', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialdocumento',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Documento creado'), ('EDITADO', 'Documento editado'), ('ARCHIVO_CARGADO', 'Archivo cargado'), ('ENVIADO_PROCESAMIENTO', 'Enviado a procesamiento'), ('ESTADO_CAMBIADO', 'Estado cambiado'), ('PROCESAMIENTO_INICIADO', 'Procesamiento iniciado'), ('PROCESAMIENTO_COMPLETADO', 'Procesamiento completado'), ('PROCESAMIENTO_ERROR', 'Error de procesamiento'), ('EXTRACCION_INICIADA', 'Extracción jurídica iniciada'), ('EXTRACCION_COMPLETADA', 'Extracción jurídica completada'), ('EXTRACCION_ERROR', 'Error de extracción jurídica'), ('CALIDAD_INICIADA', 'Control de calidad iniciado'), ('CALIDAD_COMPLETADA', 'Control de calidad completado'), ('CALIDAD_ERROR', 'Error de control de calidad'), ('DUPLICADO_DETECTADO', 'Duplicado detectado'), ('CONVERSION_INICIADA', 'Conversión a Word iniciada'), ('CONVERSION_COMPLETADA', 'Conversión a Word completada'), ('CONVERSION_ERROR', 'Error de conversión a Word'), ('DESCARTADO', 'Documento descartado')], max_length=30),
        ),
        migrations.CreateModel(
            name='ResultadoConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_COLA', 'En cola'), ('CONVIRTIENDO', 'Convirtiendo'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], db_index=True, default='EN_COLA', max_length=20)),
                ('tarea_id', models.CharField(blank=True, default='', max_length=255)),
                ('nomenclatura_completa', models.TextField(blank=True, default='')),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=500)),
                ('carpeta_materia', models.CharField(blank=True, default='', max_length=200)),
                ('archivo', models.FileField(blank=True, max_length=1000, null=True, storage=apps.normativa.storage.NormativaFinalStorage(), upload_to=apps.normativa.models.archivo_final_path)),
                ('ruta_relativa', models.CharField(blank=True, default='', max_length=1000)),
                ('hash_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('iniciado_at', models.DateTimeField(blank=True, null=True)),
                ('finalizado_at', models.DateTimeField(blank=True, null=True)),
                ('duracion_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error_codigo', models.CharField(blank=True, default='', max_length=60)),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('detalles_tecnicos', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_conversion', to='normativa.documento')),
            ],
            options={
                'verbose_name': 'resultado de conversión final',
                'verbose_name_plural': 'resultados de conversión final',
                'ordering': ('-updated_at',),
            },
        ),
    ]
