# Generated by Django 6.0.6 on 2026-07-02 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuentes', '0002_ejecucionfuente_documentos_descargados_and_more'),
        ('normativa', '0007_alter_documento_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdocumento',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Documento creado'), ('EDITADO', 'Documento editado'), ('ARCHIVO_CARGADO', 'Archivo cargado'), ('DESCARGADO_AUTOMATICAMENTE', 'Descargado automáticamente'), ('ENVIADO_PROCESAMIENTO', 'Enviado a procesamiento'), ('ESTADO_CAMBIADO', 'Estado cambiado'), ('PROCESAMIENTO_INICIADO', 'Procesamiento iniciado'), ('PROCESAMIENTO_COMPLETADO', 'Procesamiento completado'), ('PROCESAMIENTO_ERROR', 'Error de procesamiento'), ('EXTRACCION_INICIADA', 'Extracción jurídica iniciada'), ('EXTRACCION_COMPLETADA', 'Extracción jurídica completada'), ('EXTRACCION_ERROR', 'Error de extracción jurídica'), ('CALIDAD_INICIADA', 'Control de calidad iniciado'), ('CALIDAD_COMPLETADA', 'Control de calidad completado'), ('CALIDAD_ERROR', 'Error de control de calidad'), ('DUPLICADO_DETECTADO', 'Duplicado detectado'), ('CONVERSION_INICIADA', 'Conversión a Word iniciada'), ('CONVERSION_COMPLETADA', 'Conversión a Word completada'), ('CONVERSION_ERROR', 'Error de conversión a Word'), ('DESCARTADO', 'Documento descartado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='origendocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenes', to='normativa.documento'),
        ),
        migrations.AddConstraint(
            model_name='origendocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'fuente', 'seccion', 'url_origen'), name='normativa_origen_documento_unico'),
        ),
    ]
