# Generated by Django 6.0.6 on 2026-07-02 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0008_alter_historialdocumento_accion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_PROCESAMIENTO', 'Pendiente de procesamiento'), ('PROCESANDO', 'Procesando'), ('PENDIENTE_EXTRACCION', 'Pendiente de extracción jurídica'), ('PENDIENTE_REVISION', 'Pendiente de revisión'), ('CONTROL_CALIDAD', 'Control de calidad'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación jurídica'), ('LISTO_PARA_CONVERSION', 'Listo para conversión'), ('PENDIENTE_REVISION_RAPIDA', 'Pendiente de revisión rápida'), ('OBSERVADO', 'Observado'), ('DUPLICADO_CONFIRMADO', 'Duplicado confirmado'), ('CONVIRTIENDO', 'Convirtiendo a Word'), ('ERROR_CONVERSION', 'Error de conversión'), ('FINALIZADO', 'Finalizado'), ('VALIDADO', 'Validado'), ('ERROR', 'Error'), ('DESCARTADO', 'Descartado')], db_index=True, default='PENDIENTE_PROCESAMIENTO', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialdocumento',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Documento creado'), ('EDITADO', 'Documento editado'), ('ARCHIVO_CARGADO', 'Archivo cargado'), ('DESCARGADO_AUTOMATICAMENTE', 'Descargado automáticamente'), ('ENVIADO_PROCESAMIENTO', 'Enviado a procesamiento'), ('ESTADO_CAMBIADO', 'Estado cambiado'), ('PROCESAMIENTO_INICIADO', 'Procesamiento iniciado'), ('PROCESAMIENTO_COMPLETADO', 'Procesamiento completado'), ('PROCESAMIENTO_ERROR', 'Error de procesamiento'), ('EXTRACCION_INICIADA', 'Extracción jurídica iniciada'), ('EXTRACCION_COMPLETADA', 'Extracción jurídica completada'), ('EXTRACCION_ERROR', 'Error de extracción jurídica'), ('CALIDAD_INICIADA', 'Control de calidad iniciado'), ('CALIDAD_COMPLETADA', 'Control de calidad completado'), ('CALIDAD_ERROR', 'Error de control de calidad'), ('REVISION_INICIADA', 'Revisión jurídica iniciada'), ('CAMPO_JURIDICO_EDITADO', 'Campo jurídico editado'), ('ALERTA_REVISADA', 'Alerta revisada'), ('REVISION_APROBADA', 'Revisión jurídica aprobada'), ('REVISION_DEVUELTA', 'Revisión jurídica devuelta'), ('DUPLICADO_DETECTADO', 'Duplicado detectado'), ('CONVERSION_INICIADA', 'Conversión a Word iniciada'), ('CONVERSION_COMPLETADA', 'Conversión a Word completada'), ('CONVERSION_ERROR', 'Error de conversión a Word'), ('DESCARTADO', 'Documento descartado')], max_length=30),
        ),
        migrations.CreateModel(
            name='RevisionJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_revision', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('APROBADA', 'Aprobada'), ('DEVUELTA', 'Devuelta con observaciones')], db_index=True, default='EN_CURSO', max_length=15)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('motivo_devolucion', models.TextField(blank=True, default='')),
                ('ficha_anterior', models.JSONField(blank=True, default=dict)),
                ('ficha_aprobada', models.JSONField(blank=True, default=dict)),
                ('iniciada_at', models.DateTimeField(auto_now_add=True)),
                ('finalizada_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_juridicas', to='normativa.documento')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_juridicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'revisión jurídica',
                'verbose_name_plural': 'revisiones jurídicas',
                'ordering': ('-numero_revision', '-iniciada_at'),
            },
        ),
        migrations.CreateModel(
            name='DecisionAlertaRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada justificadamente')], max_length=15)),
                ('justificacion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_revision', to='normativa.alertacalidad')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones_alertas', to='normativa.revisionjuridica')),
            ],
            options={
                'verbose_name': 'decisión de alerta jurídica',
                'verbose_name_plural': 'decisiones de alertas jurídicas',
                'ordering': ('alerta__severidad', 'alerta_id'),
            },
        ),
        migrations.CreateModel(
            name='CambioRevisionJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=40)),
                ('valor_anterior', models.TextField(blank=True, default='')),
                ('valor_nuevo', models.TextField(blank=True, default='')),
                ('origen_valor', models.CharField(choices=[('PROPUESTA', 'Propuesta automática'), ('CORRECCION_MANUAL', 'Corrección manual'), ('SIN_CAMBIO', 'Confirmado sin cambio')], max_length=20)),
                ('confianza_propuesta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='normativa.revisionjuridica')),
            ],
            options={
                'verbose_name': 'cambio de revisión jurídica',
                'verbose_name_plural': 'cambios de revisiones jurídicas',
                'ordering': ('campo',),
            },
        ),
        migrations.AddConstraint(
            model_name='revisionjuridica',
            constraint=models.UniqueConstraint(fields=('documento', 'numero_revision'), name='normativa_revision_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='revisionjuridica',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'EN_CURSO')), fields=('documento',), name='normativa_una_revision_activa'),
        ),
        migrations.AddConstraint(
            model_name='decisionalertarevision',
            constraint=models.UniqueConstraint(fields=('revision', 'alerta'), name='normativa_decision_revision_alerta_unica'),
        ),
        migrations.AddConstraint(
            model_name='cambiorevisionjuridica',
            constraint=models.UniqueConstraint(fields=('revision', 'campo'), name='normativa_cambio_revision_campo_unico'),
        ),
    ]
